# NPTEL R Programming – Week 10 Complete Experiment

**Source:** NPTEL *Foundations of R Software* notes provided by the user.

This Colab notebook is intentionally divided into **separate executable slots/cells**.  
Run them **one by one from top to bottom**.

Topics covered from the notes:
1. String substitution – `sub()`
2. Global string substitution – `gsub()`
3. String searching – `grep()`
4. Case-sensitive / case-insensitive `grep()`
5. `grepl()`
6. Data frames using the `MASS::painters` dataset
7. Data-frame inspection: row names, columns, numeric/factor checks, summary
8. `attach()` and `detach()`
9. Data-frame subsetting
10. Selecting/removing columns with `subset()`
11. Splitting a data frame with `split()`
12. Combining data frames using `cbind()`
13. Merging data frames using `merge()`
14. Combining data frames vertically using `rbind()`

**Important:** Each practical operation is kept in its own code cell, not combined into one large program.

## SLOT 1 – String Substitution using `sub()`
The notes explain that `sub()` replaces only the **first occurrence** of a matching substring.

In [1]:
y <- "Number of participants: 25"
sub("25", "30", y)

[1] "Number of participants: 30"

## SLOT 2 – `sub()` with repeated text
Only the first `Mr. Singh` is replaced.

In [2]:
y <- "Mr. Singh is the smart one. Mr. Singh is funny, too."
sub("Mr. Singh", "Professor Jha", y)

[1] "Professor Jha is the smart one. Mr. Singh is funny, too."

## SLOT 3 – Global Substitution using `gsub()`
`gsub()` replaces **all occurrences** of the matching substring.

In [3]:
y <- "Mr. Singh is the smart one. Mr. Singh is funny, too."
gsub("Mr. Singh", "Professor Jha", y)

[1] "Professor Jha is the smart one. Professor Jha is funny, too."

## SLOT 4 – `grep()` with `value = TRUE`
Returns the actual matching strings.

In [4]:
str <- c("R Course", "exercises", "include examples of R language")
grep("ex", str, value = TRUE)

[1] "exercises"                      "include examples of R language"

## SLOT 5 – `grep()` with `value = FALSE`
Returns the **indices/positions** of matching elements.

In [5]:
str <- c("R Course", "exercises", "include examples of R language")
grep("ex", str, value = FALSE)

[1] 2 3

## SLOT 6 – `grep()` and `ignore.case`
Case-sensitive matching is used when `ignore.case = FALSE`.

In [6]:
str <- c("R Course", "exercises", "include examples of r language", "in R software.")
grep("R", str, ignore.case = FALSE, value = TRUE)

[1] "R Course"       "in R software."

## SLOT 7 – Case-insensitive `grep()`
With `ignore.case = TRUE`, both upper- and lower-case `R` are matched.

In [7]:
grep("R", str, ignore.case = TRUE, value = TRUE)

[1] "R Course"                       "exercises"
[3] "include examples of r language" "in R software."

## SLOT 8 – `grep()` returning indices
Compare the indices for case-insensitive and case-sensitive matching.

In [8]:
grep("R", str, ignore.case = TRUE, value = FALSE)

[1] 1 2 3 4

In [9]:
grep("R", str, ignore.case = FALSE, value = FALSE)

[1] 1 4

## SLOT 9 – `grep()` on combined strings
The notes use `c(x, y)` to combine two strings and then search them.

In [10]:
x <- "R course 24.07.2021"
y <- "Number of participants: 25"
c(x, y)
grep("our", c(x, y))

[1] "R course 24.07.2021"        "Number of participants: 25"

[1] 1

## SLOT 10 – `grep()` for `Num`

In [11]:
x <- "R course 24.07.2022"
y <- "Number of participants: 50"
grep("Num", c(x, y))

[1] 2

## SLOT 11 – `grepl()`
`grepl()` gives a logical result (`TRUE`/`FALSE`) for each element.

In [12]:
str <- c("R Course", "exercises", "include examples of R language")
grepl("R", str)

[1]  TRUE FALSE  TRUE

## SLOT 12 – `grepl()` for another pattern

In [13]:
grepl("ex", str)

[1] FALSE  TRUE  TRUE

# PART B – DATA FRAMES

The NPTEL notes describe a data frame as a data-set object where columns contain variables and rows contain observations. The `MASS` package provides the `painters` example dataset.

## SLOT 13 – Load `MASS` and display `painters`

In [14]:
library(MASS)
painters

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A
F. Zucarro      10          13       8      8         B
Fr. Salviata    13          15       8      8         B
Parmigiano      10          15       6      6         B
Primaticcio     15          14       7     10         B
T. Zucarro      13          14      10      9         B
Volterra        12          15       5      8         B
Barocci         14          15       6     10         C
Cortona         16          14      12      6         C
Josepin         10          10       6      2         C
L. Jordaens     13          12       9      6         C
Testa           11          15       0      6         C
Vanius          15          15      12     13         C
Bassano          6           8      17      0         D
Bellini          4           6      14      0         D
Giorgione        8           9      18      4         D
Murillo          6           8      15      4         D
Palma Giovane   12           9      14      6         D
Palma Vecchio    5           6      16      0         D
Pordenone        8          14      17      5         D
Tintoretto      15          14      16      4         D
Titian          12          15      18      6         D
Veronese        15          10      16      3         D
Albani          14          14      10      6         E
Caravaggio       6           6      16      0         E
Corregio        13          13      15     12         E
Domenichino     15          17       9     17         E
Guercino        18          10      10      4         E
Lanfranco       14          13      10      5         E
The Carraci     15          17      13     13         E
Durer            8          10      10      8         F
Holbein          9          10      16     13         F
Pourbus          4          15       6      6         F
Van Leyden       8           6       6      4         F
Diepenbeck      11          10      14      6         G
J. Jordaens     10           8      16      6         G
Otho Venius     13          14      10     10         G
Rembrandt       15           6      17     12         G
Rubens          18          13      17     17         G
Teniers         15          12      13      6         G
Van Dyck        15          10      17     13         G
Bourdon         10           8       8      4         H
Le Brun         16          16       8     16         H
Le Suer         15          15       4     15         H
Poussin         15          17       6     15         H

## SLOT 14 – Display row names
The painter names are row identifiers, not variables/columns.

In [15]:
rownames(painters)

 [1] "Da Udine"        "Da Vinci"        "Del Piombo"      "Del Sarto"
 [5] "Fr. Penni"       "Guilio Romano"   "Michelangelo"    "Perino del Vaga"
 [9] "Perugino"        "Raphael"         "F. Zucarro"      "Fr. Salviata"
[13] "Parmigiano"      "Primaticcio"     "T. Zucarro"      "Volterra"
[17] "Barocci"         "Cortona"         "Josepin"         "L. Jordaens"
[21] "Testa"           "Vanius"          "Bassano"         "Bellini"
[25] "Giorgione"       "Murillo"         "Palma Giovane"   "Palma Vecchio"
[29] "Pordenone"       "Tintoretto"      "Titian"          "Veronese"
[33] "Albani"          "Caravaggio"      "Corregio"        "Domenichino"
[37] "Guercino"        "Lanfranco"       "The Carraci"     "Durer"
[41] "Holbein"         "Pourbus"         "Van Leyden"      "Diepenbeck"
[45] "J. Jordaens"     "Otho Venius"     "Rembrandt"       "Rubens"
[49] "Teniers"         "Van Dyck"        "Bourdon"         "Le Brun"
[53] "Le Suer"         "Poussin"

## SLOT 15 – Check whether `School` is numeric

In [16]:
is.numeric(painters$School)

[1] FALSE

## SLOT 16 – Check whether `Drawing` is numeric

In [17]:
is.numeric(painters$Drawing)

[1] TRUE

## SLOT 17 – Check whether `School` is a factor

In [18]:
is.factor(painters$School)

[1] TRUE

## SLOT 18 – Check whether `Drawing` is a factor

In [19]:
is.factor(painters$Drawing)

[1] FALSE

## SLOT 19 – Display column names

In [20]:
colnames(painters)

[1] "Composition" "Drawing"     "Colour"      "Expression"  "School"

## SLOT 20 – Summary of the complete data frame

In [21]:
summary(painters)

  Composition       Drawing          Colour        Expression         School
 Min.   : 0.00   Min.   : 6.00   Min.   : 0.00   Min.   : 0.000   A      :10
 1st Qu.: 8.25   1st Qu.:10.00   1st Qu.: 7.25   1st Qu.: 4.000   D      :10
 Median :12.50   Median :13.50   Median :10.00   Median : 6.000   E      : 7
 Mean   :11.56   Mean   :12.46   Mean   :10.94   Mean   : 7.667   G      : 7
 3rd Qu.:15.00   3rd Qu.:15.00   3rd Qu.:16.00   3rd Qu.:11.500   B      : 6
 Max.   :18.00   Max.   :18.00   Max.   :18.00   Max.   :18.000   C      : 6
                                                                  (Other): 8

## SLOT 21 – Summary of the categorical variable `School`

In [22]:
summary(painters$School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

## SLOT 22 – Attach the data frame
After `attach()`, column names can be used directly without `painters$`.

In [23]:
attach(painters)
summary(School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

## SLOT 23 – Summary of `Composition` after `attach()`

In [24]:
summary(Composition)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

## SLOT 24 – Detach the data frame
This restores the default setting; after detaching, use `painters$ColumnName` again.

In [25]:
detach(painters)

## SLOT 25 – Subset: painters from School F
The notes use `subset()` with the logical equality operator `==`.

In [26]:
subset(painters, School == "F")

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

## SLOT 26 – Equivalent subset using indexing

In [27]:
painters[painters[["School"]] == "F", ]

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

## SLOT 27 – Subset using a numeric condition
Select painters whose `Composition <= 6`.

In [28]:
subset(painters, Composition <= 6)

              Composition Drawing Colour Expression School
Fr. Penni     0           15       8     0          A
Perugino      4           12      10     4          A
Bassano       6            8      17     0          D
Bellini       4            6      14     0          D
Murillo       6            8      15     4          D
Palma Vecchio 5            6      16     0          D
Caravaggio    6            6      16     0          E
Pourbus       4           15       6     6          F

## SLOT 28 – Select useful columns only
The notes remove the 3rd and 5th columns (`Colour` and `School`) from the School F subset.

In [29]:
subset(painters, School == "F", select = c(-3, -5))

           Composition Drawing Expression
Durer      8           10       8
Holbein    9           10      13
Pourbus    4           15       6
Van Leyden 8            6       4

## SLOT 29 – Split the data frame by `School`
`split()` partitions the data according to the values of a variable.

In [30]:
splitted <- split(painters, painters$School)
splitted

$A
                Composition Drawing Colour Expression School
Da Udine                 10       8     16          3      A
Da Vinci                 15      16      4         14      A
Del Piombo                8      13     16          7      A
Del Sarto                12      16      9          8      A
Fr. Penni                 0      15      8          0      A
Guilio Romano            15      16      4         14      A
Michelangelo              8      17      4          8      A
Perino del Vaga          15      16      7          6      A
Perugino                  4      12     10          4      A
Raphael                  17      18     12         18      A

$B
             Composition Drawing Colour Expression School
F. Zucarro            10      13      8          8      B
Fr. Salviata          13      15      8          8      B
Parmigiano            10      15      6          6      B
Primaticcio           15      14      7         10      B
T. Zucarro            13      14     10          9      B
Volterra              12      15      5          8      B

$C
            Composition Drawing Colour Expression School
Barocci              14      15      6         10      C
Cortona              16      14     12          6      C
Josepin              10      10      6          2      C
L. Jordaens          13      12      9          6      C
Testa                11      15      0          6      C
Vanius               15      15     12         13      C

$D
              Composition Drawing Colour Expression School
Bassano                 6       8     17          0      D
Bellini                 4       6     14          0      D
Giorgione               8       9     18          4      D
Murillo                 6       8     15          4      D
Palma Giovane          12       9     14          6      D
Palma Vecchio           5       6     16          0      D
Pordenone               8      14     17          5      D
Tintoretto             15      14     16          4      D
Titian                 12      15     18          6      D
Veronese               15      10     16          3      D

$E
            Composition Drawing Colour Expression School
Albani               14      14     10          6      E
Caravaggio            6       6     16          0      E
Corregio             13      13     15         12      E
Domenichino          15      17      9         17      E
Guercino             18      10     10          4      E
Lanfranco            14      13     10          5      E
The Carraci          15      17     13         13      E

$F
           Composition Drawing Colour Expression School
Durer                8      10     10          8      F
Holbein              9      10     16         13      F
Pourbus              4      15      6          6      F
Van Leyden           8       6      6          4      F

$G
            Composition Drawing Colour Expression School
Diepenbeck           11      10     14          6      G
J. Jordaens          10       8     16          6      G
Otho Venius          13      14     10         10      G
Rembrandt            15       6     17         12      G
Rubens               18      13     17         17      G
Teniers              15      12     13          6      G
Van Dyck             15      10     17         13      G

$H
        Composition Drawing Colour Expression School
Bourdon          10       8      8          4      H
Le Brun          16      16      8         16      H
Le Suer          15      15      4         15      H
Poussin          15      17      6         15      H

## SLOT 30 – Check one split object
Each object such as `splitted$A` is itself a data frame.

In [31]:
is.data.frame(splitted$A)

[1] TRUE

# PART C – COMBINING AND MERGING DATA FRAMES

The notes give three main techniques:
- `cbind()` → combine columns side-by-side
- `merge()` → join using a common column
- `rbind()` → stack rows vertically

## SLOT 31 – Create `df1`

In [32]:
df1 <- data.frame(
  state = c("UP", "MP", "AP", "JK"),
  popnsize = c(1000, 2000, 3000, 4000)
)
df1

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

## SLOT 32 – Create `df2`

In [33]:
df2 <- data.frame(
  state = c("UP", "MP", "AP", "JK"),
  samplesize = c(100, 200, 300, 400),
  surveycompleted = c("Yes", "No", "Yes", "No")
)
df2

  state samplesize surveycompleted
1 UP    100        Yes
2 MP    200        No
3 AP    300        Yes
4 JK    400        No

## SLOT 33 – `cbind()`
Combines the two data frames side-by-side.

In [34]:
cbind(df1, df2)

  state popnsize state samplesize surveycompleted
1 UP    1000     UP    100        Yes
2 MP    2000     MP    200        No
3 AP    3000     AP    300        Yes
4 JK    4000     JK    400        No

## SLOT 34 – `merge()` using common column `state`
The common column is used to join the two data frames.

In [35]:
merge(df1, df2, by = "state")

  state popnsize samplesize surveycompleted
1 AP    3000     300        Yes
2 JK    4000     400        No
3 MP    2000     200        No
4 UP    1000     100        Yes

## SLOT 35 – Create `df11` for vertical combining

In [36]:
df11 <- data.frame(
  state = c("UP", "MP", "AP", "JK"),
  popnsize = c(1000, 2000, 3000, 4000)
)
df11

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

## SLOT 36 – Create `df22`

In [37]:
df22 <- data.frame(
  state = c("Bihar", "Delhi", "Punjab"),
  popnsize = c(100, 200, 300)
)
df22

  state  popnsize
1 Bihar  100
2 Delhi  200
3 Punjab 300

## SLOT 37 – `rbind()`
Stacks the rows of `df22` below `df11`.

In [38]:
rbind(df11, df22)

  state  popnsize
1 UP     1000
2 MP     2000
3 AP     3000
4 JK     4000
5 Bihar   100
6 Delhi   200
7 Punjab  300

# QUICK REVISION – WHAT TO REMEMBER

| Function | Main use |
|---|---|
| `sub()` | Replace **first** matching occurrence |
| `gsub()` | Replace **all** matching occurrences |
| `grep()` | Find matching elements / indices |
| `grepl()` | Return `TRUE/FALSE` for matches |
| `summary()` | Quick summary of variables |
| `subset()` | Select rows/columns based on conditions |
| `split()` | Divide a data frame into groups |
| `cbind()` | Combine data frames **side-by-side** |
| `merge()` | Join data frames using a common column |
| `rbind()` | Stack data frames **vertically** |

**Run every code cell separately** to perform the complete Week 10 practical content represented in the supplied NPTEL notes.