
Adition with data vectors

In [1]:
c(2,3,5,7) + c(-2,-3,-5,8)

[1]  0  0  0 15

R is a calculator

In [2]:
2^3

[1] 8

In [3]:
2**3

[1] 8

In [4]:
2^0.5

[1] 1.414214

In [5]:
2**0.5

[1] 1.414214

In [6]:
2^-0.5

[1] 0.7071068

Power operation with scalar

In [7]:
c(2,3,5,7)^2

[1]  4  9 25 49

Power operation with vector

In [8]:
c(2,3,5,7)^c(2,3)

[1]   4  27  25 343

Power operation with vector

In [9]:
c(1,2,3,4,5,6)^c(2,3,4)

[1]    1    8   81   16  125 1296

Power operation with vector

In [10]:
c(2,3,5,7)^c(2,3,4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

Integer division with scalar

In [11]:
c(2,3,5,7) %/% 2

[1] 1 1 2 3

Integer division with data vector

In [12]:
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 2

Interger division with data vector

In [13]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

Modulo Division (x mod y) with scalars

In [14]:
c(2,3,5,7) %% 2

[1] 0 1 1 1

Modulo Division (x mod y) with data vectors

In [15]:
c(2,3,5,7) %% c(2,3)

[1] 0 0 1 1

Modulo Division (x mod y) with data vectors

In [16]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

Maximun

In [17]:
max(1.2, 3.4, -7.8)

[1] 3.4

In [18]:
max(c(1.2, 3.4, -7.8))

[1] 3.4

Minimum

In [19]:
min(1.2, 3.4, -7.8)

[1] -7.8

In [20]:
min(c(1.2, 3.4, -7.8))

[1] -7.8

Arithmetic Mean

In [21]:
mean(2,3,4)

[1] 2

In [22]:
mean(c(2,3,4))

[1] 3

abs for finding the absolute values

In [23]:
abs(-4)

[1] 4

In [24]:
abs(c(-1,-2,-3,4,5))

[1] 1 2 3 4 5

sqrt for finding the square root of values

In [25]:
sqrt(4)

[1] 2

In [26]:
sqrt(c(4,9,16,25))

[1] 2 3 4 5

rounds for finding the round of values

In [27]:
round(1.23)

[1] 1

In [28]:
round(1.83)

[1] 2

log for finding the natural log(ln) of values

In [29]:
log(10)

[1] 2.302585

In [30]:
log(exp(1))

[1] 1

In [31]:
log(c(10,100,1000))

[1] 2.302585 4.605170 6.907755

log10 for finding the log (with base 10) of value

In [32]:
log10(10)

[1] 1

In [33]:
log10(100)

[1] 2

In [34]:
log10(c(10,100,1000))

[1] 1 2 3

An assignment can also be used to save

In [35]:
x1 = c(1,2,3,4)
x1

[1] 1 2 3 4

In [36]:
x2 = x1^2
x2

[1]  1  4  9 16

Assignment calculation with scalar ,data vector and built in function also work

In [37]:
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))

[1] 21 22 23 24

In [38]:
abs( c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2)) )

[1] 19 18 17 16

Entering data row wise in a matrix

In [39]:
y = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8), byrow = TRUE)

y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [40]:
x = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [41]:
x = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8), byrow = FALSE)
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [42]:
x = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8) )

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

Properties of a Matrix

In [43]:
dim(x) # tells the dimension of matrix

[1] 4 2

In [44]:
nrow(x) # tells the number of rows

[1] 4

In [45]:
ncol(x) # tells the number of columns

[1] 2

In [46]:
mode(x)

[1] "numeric"

In [47]:
attributes(x) #Informs the dimension of matrix

$dim
[1] 4 2

In [48]:
help("matrix")